# Generated by Django 3.1.2 on 2020-10-12 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=59)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.district')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('specifications', models.TextField()),
                ('phone', models.CharField(max_length=17)),
                ('price', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('image', models.ImageField(default='default.jpg', upload_to='product/images')),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='product.category')),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='district_set', to='product.district')),
                ('subdistrict', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict_set', to='product.subdistrict')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='post_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
