# Generated by Django 3.1.2 on 2020-10-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_set', to='product.district'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subdistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict_set', to='product.subdistrict'),
        ),
    ]
