# Generated by Django 3.1.2 on 2020-10-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201012_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdistrict_set', to='product.subdistrict'),
        ),
    ]
