# Generated by Django 3.1.2 on 2020-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201012_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subdistrict',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
