# Generated by Django 3.1.2 on 2020-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201017_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='1', max_length=17),
        ),
    ]
