# Generated by Django 3.1.2 on 2020-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_orderitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Arrived', 'Arrived')], default='Ordered', max_length=100),
        ),
    ]
