# Generated by Django 3.1.2 on 2020-10-19 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201019_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_of_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
