# Generated by Django 3.1.2 on 2020-10-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='m@f.c', max_length=254),
            preserve_default=False,
        ),
    ]
